name: Tests

on:
  push:
  workflow_dispatch:
  pull_request:

concurrency:
  group: tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  ACTION_TOKEN: ${{ github.token }}

jobs:
  phpcsfixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
        with:
          path: src/

  trunk:
    name: Trunk Check Runner
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations

    steps:
      - uses: actions/checkout@v3
      - uses: trunk-io/trunk-action@v1
